(function() {
	var css;
	if(true){
var cssd = [
        " /* Full wide start */",
				
         "/Individual Post/ ",
	".ltEKP .QBXjJ{",
	"    border: none;",
	"}",
	"._8-yf5 [d=\"M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z\"]{",
	"	filter: invert(0) !important;",
	"    fill: #12B6A9 !important;",
	"}",
	".JyscU.ePUX4 .UE9AK{",
	"    background-color: var(--bg3-color) !important;",
	"    border-left: none;",
	"    border-bottom: none;",
	"}",
	".JyscU.ePUX4 .eo2As{",
	"    border-left: none;",
	"    border-top: none;",
	"}",
	".JyscU .Slqrh{",
	"    border-top: none;",
	"}",
	"",
	"._9AhH0 {",
	"    display: none;",
	"}",
	"",
	".PyenC, .fXIG0 {",
	"    height: 135px;",
	"    left: 50%;",
	"    margin-left: 240px;",
	"    margin-top: 316px;",
	"    top: 50%;",
	"    width: 135px;",
	"    z-index: 1;",
	"}",
	"",
	".PdwC2 {",
	"    max-width: 65% !important;",
	"    max-height: 100% !important;",
	"}",
	"",
	".JyscU ._97aPb,.eLAPa,.pR7Pc, .rQDP3  {",
	"    max-height: 100% !important;",
	"}",
	".glyphsSpriteDirect__outline__24__grey_9, .glyphsSpriteFacebook_circle__outline__24__grey_9, .glyphsSpriteFacebook_circle_filled_24, .glyphsSpriteApp_messenger__outline__24__grey_9, .glyphsSpriteApp_twitter__outline__24__grey_9, .glyphsSpriteMail__outline__24__grey_9, .glyphsSpriteLink__outline__24__grey_9, .glyphsSpriteLite_app_icon{",
	"    filter: invert(1);",
	"}",
	"",
    "/Individual Post/", 
        /*-------------------------------------------------------------------------------------------------------------------------------------------------------*/

        /*----------------------------------------------------------------------------------------------------------------------------------------------------*/
        ".-V_eO{",
        "opacity:0 !important;",
        "}",

        "body /* to even out with the scrollbar container width */ {",
        "    margin-left:6px;",
        "}",
        ".M9sTE  .L_LMM  .JyscU  .ePUX4{",
        "    width:100%!important;",
        "    max-width:none!important;",
        "    padding:0!important;",
        "    margin:2.5px 5px!important;",
        "}",
        "body /* roboto as font */ {",
        "    font-family:roboto;",
        "    text-rendering:geometricPrecision; ",
        "}",
        ".v9tJq /* stretches posts grid to the full width of the screen */ {",
        "    max-width:none!important;",
        "    padding:0!important;",
        "    width:100%!important;",
        "}",
        "._bz0w, .weEfm, .v9tJq  /* removes margins from posts */ {",
        "    margin:2.5px 5px!important;",
        "}",
        ":focus /* hides ugly blue outline from elements which are in focus currently */ {",
        "    outline:0;",
        "}",
        ".vtbgv /* adds a margin between sticky header and profile header */ {",
        "    margin-top:44px;",
        "}",
        ".aUCRo /* hides the sticky header when scrolling past profile header */, ._49XvD, .iHqQ7, .SkY6J /* hides stories, follow suggestions and instagram links from the homepage sidebar */ {",
        "    display:none;",
        "}",
        ".qqm6D /* centers higlights */ {",
        "    margin:0 auto;",
        "}",
        ".KQA-S, ._1MzIy, ._3MPWk, ._8Rm4L, .zMhqu /* border radius for posts */ {",
        "    border-radius:16px !important;",
        "}",
        ".JYWcJ, .JYWcJ:link, .JYWcJ:visited /* sets font weight to regular on photo tags */ {",
        "    font-weight:400;",
        "}",
        "  /* scrollbar css */",
        "  /* total width */",
        "::-webkit-scrollbar {width:6px}",
        "::-webkit-scrollbar:horizontal {height:6px}",
        "",
        "/* background of the scrollbar except button or resizer */",
        "::-webkit-scrollbar-track {background-color:rgba(232,232,232,.2)}",
        "::-webkit-scrollbar-track:horizontal {background-color:rgba(232,232,232,.2)}",
        "",
        "/* scrollbar itself */",
        "::-webkit-scrollbar-thumb {background-color:rgba(152,152,152);border-radius:16px;width:6px;transition:all 3s ease}",
        "::-webkit-scrollbar-thumb:hover {background-color:rgba(104,104,104)}",
        "",
        "/* set button(top and bottom of the scrollbar) */",
        "::-webkit-scrollbar-button {display:none}",
        " /* scrollbar css end */",
        " /* Full wide end */",
        "body{",
        "background: black !important;",
        "}",
        "",
        "/*variables 1*/",
        "",
        ".sDN5V {",
        "    /*variables modification*/",
        "    ",
        " /* the panels and the navigation bar */ ",
        "    --d87: 0,0,0!important;",
        " /* background  */",
        "    --b3f: 5,5,5!important;",
        " /* general borders I think */",
        "    --b6a: 30,30,30!important;",
        " /* border that goes for photos */",
        "    --ce3: 30,30,30 !important;",
        " /* Name of the Stories */",
        "    --i1d: 255,255,255 !important;",
        " /* white bar in the activities part */",
        "    --f23: 0,0,0!important;",
        " /* likes */",
        "    --f75: 255,255,255;",
        " /* mention */",
        "    --fe0: 245,245,245 !important;",
        " /* I sew up the photos in the profiles */",
        "    --b38: 100,100,100 !important;",
        " /* chat selected */",
        "    --bb2: 20,20,20!important;",
        "",
        "    ",
        "    /*------------------------------*/",
        "    --edc: 199,199,199;",
        "    --ca6: 219,219,219;",
        "    --cdd: 38,38,38;",
        "    --e22: 199,199,199;",
        "    --e62: 245,251,255;",
        "    --b2f: 88,195,34;",
        "    --c8c: 168,168,168;",
        "    --jd9: 0,0,0;",
        "    --j64: 54,54,54;",
        "    --a97: 243,243,243;",
        "    --d20: 38,38,38;",
        "}",
        "",
        "/*Variables 2*/",
        ".ekjoN, .sDN5V {",
        "     /*variables modification*/",
        "",
        "    /*search bar */",
        "    --f52: 161,161,161 !important;",
        "	/*multimedia background */",
        "    --jb7: 10,10,10 !important;",
        "   /*when you share*/",
        "    --fa7: 27,41,52;",
        "",
        "",
        "	/*---------------------------------*/",
        "    --h1d: 255,255,255;",
        "    --de5: 255,255,255;",
        "    --d69: 0,149,246;",
        "    --b86: 88,195,34;",
        "    --i30: 237,73,86;",
        "    --d62: 255,255,255;",
        "    --e4f: 54,54,54;",
        "    --a72: 255,255,255;",
        "    --ie3: 142,142,142;",
        "    --c37: 237,73,86;",
        "    --f24: 0,149,246;",
        "    --jbb: 53,121,234;",
        "    --eca: 255,255,255;",
        "    --ba8: 168,168,168;",
        "    --eac: 237,73,86;",
        "}",
        "/*Homepage*/",
        "",
        "",
        "",
        "/*scroll bar*/",
        "",
        "*::-webkit-scrollbar {",
        "	width: 15px;",
        "	background:#121212;",
        "",
        "}",
        "",
        "*::-webkit-scrollbar-thumb {",
        "	background: rgba(255,255,255,.3);",
        "}",
        "",
        "/*LOGO*/",
        ".s4Iyt {",
        "    filter: invert(1) !important;",
        "}",
        "",
        "/*three dots of more options and the other icons on the navigation bar*/",
        "",
        "",
        "a > ._8-yf5 {",
        "    fill: rgb(255,255,255) !important;",
        "}",
        "div > ._8-yf5 {",
        "    fill: rgb(255,255,255) !important;",
        "}",
        "",
        "",
        
        "span svg[aria-label=\"Me gusta\"], span svg[aria-label=\"Like\"], span svg[aria-label=\"Hou van\"], span svg[aria-label=\"To se mi líbí\"], span svg[aria-label=\"Synes godt om\"], span svg[aria-label=\"Gefällt mir\"], span svg[aria-label=\"Μου αρέσει!\"], span svg[aria-label=\"Tykkää\"], span svg[aria-label=\"J’aime\"], span svg[aria-label=\"Suka\"], span svg[aria-label=\"Mi piace\"], span svg[aria-label=\"いいね！\"], span svg[aria-label=\"좋아요\"], span svg[aria-label=\"Liker\"], span svg[aria-label=\"Vind ik leuk\"], span svg[aria-label=\"Lubię to!\"], span svg[aria-label=\"Curtir\"], span svg[aria-label=\"Gosto\"], span svg[aria-label=\"Нравится\"], span svg[aria-label=\"Gilla\"], span svg[aria-label=\"ถูกใจ\"], span svg[aria-label=\"I-like\"], span svg[aria-label=\"Beğen\"], span svg[aria-label=\"赞\"], span svg[aria-label=\"讚\"], span svg[aria-label=\"লাইক\"], span svg[aria-label=\"પસંદ\"], span svg[aria-label=\"लाइक करें\"], span svg[aria-label=\"Sviđa mi se\"], span svg[aria-label=\"Tetszik\"], span svg[aria-label=\"ಇಷ್ಟ\"], span svg[aria-label=\"ലൈക്കുചെയ്യുക\"], span svg[aria-label=\"पसंत करा\"], span svg[aria-label=\"मनपराउनुहोस्\"], span svg[aria-label=\"ਪਸੰਦ ਕਰੋ\"], span svg[aria-label=\"කැමැත්ත\"], span svg[aria-label=\"Páči sa mi to\"], span svg[aria-label=\"விருப்பம்\"], span svg[aria-label=\"ఇష్టం\"], span svg[aria-label=\"Thích\"], span svg[aria-label=\"讚好\"], span svg[aria-label=\"Харесва ми\"], span svg[aria-label=\"Îmi place\"], span svg[aria-label=\"Свиђа ми се\"], span svg[aria-label=\"Подобається\"]{",
        " fill: rgb(255,255,255) !important;",
        "}",
        "",
        "/*.QBdPU > svg[aria-label=\"Me gusta\"], .QBdPU > svg[aria-label=\"Like\"]{",
        " fill: rgb(255,255,255) !important;",
        "}*/",
        "",
        ".ZyFrc> svg{",
        " fill: rgb(237, 73, 86) !important;",
        "}",
        "",
        "",
        "/*search bar*/",
        ".Di7vw {",
        "    background: #262626 !important;",
        "}",
        ".x3qfX {",
        "  background: #262626 !important;",
        "}",
        "",
        "/*mute video*/",
        ".IhCmn > svg{",
        "    fill: #262626 !important;",
        "}",
        "",
        "",
        "/*perfiles*/",
        "",
        "",
        "/*buttons*/",
        "span button.-fzfL {",
        "    border-color: #fff !important;",
        "}",
        ".glyphsSpriteFriend_Follow{",
        " filter: invert(1) !important;",
        "}",
        ".coreSpriteDropdownArrowGrey9{",
        " filter: invert(1) !important;",
        "}",
        "",
        "",
        ".RnEpo {",
        "    background-color: rgba(20,20,20,.65);",
        "}",
        "",
        "",
        "a, button,h2,span{",
        "    color: #ffffff !important;",
        "}",
        "",
        "/*posts*/",
        ".IhCmn {",
        "    background-color: #fff !important;",
        "}",
        "/* Big following list */",
        "body > div.RnEpo.Yx5HN > div{",
        "    max-height: 2200px !important;",
        "}",
        "span._2dbep,a._2dbep.qNELH.kIKUG{",
        "    width: 80px !important;",
        "    height: 80px !important;",
        "}",
        "canvas.CfWVH{",
        "    width: 90px !important;",
        "    height: 90px !important;",
        "}",
        "#react-root > section > main > div > header > div > div > span {",
        "    width: 150px !important;",
        "    height: 150px !important;",
        "}",
        "#react-root > section > main > div > header > div > div > canvas{",
        "    width: 168px !important;",
        "    height: 168px !important;",
        "}",
        "#react-root > section > div > div._lz6s.Hz2lF > div > div.ctQZg > div > div:nth-child(5) > span,#react-root > section > nav > div._8MQSO.Cx7Bp > div > div > div.ctQZg > div > div:nth-child(5) > span{",
        "    width: 22px !important;",
        "    height: 22px !important;",
        "}",
        "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > canvas{",
        "    width: 66px !important;",
        "    height: 66px !important;",
        "}",
        "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > a > img,#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > a{",
        "    width: 56px !important;",
        "    height: 56px !important;",
        "}",
        "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div._8UZ6e > div.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a > div > div > div > * > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > div > canvas{",
        "    width: 44px !important;",
        "    height: 44px !important;",
        "}",
        "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div._8UZ6e > div.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a > div > div > div > * > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > div > a,#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div._8UZ6e > div.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a > div > div > div > * > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > div > span{",
        "    width: 32px !important;",
        "    height: 32px !important;",
        "}",
        "#react-root > section > main > section > div.cGcGK > * > div > * > div.eo2As > section.EDfFK.ygqzn > div > div.Igw0E._56XdI.eGOV_._4EzTm.ItkAi > a > div > div > span,body > div._2dDPU.CkGkG > div.zZYga > div > article > div.eo2As > section.EDfFK.ygqzn > div > div.Igw0E._56XdI.eGOV_._4EzTm.ItkAi > a > div > div > span{",
        "    width: 20px !important;",
        "    height: 20px !important;",
        "}",

        ".theme1 {",
        "display: none !important;",
        "width: 100% !important;",
        "position: absolute !important;",
        "background-color: black !important;",
        /*
  "box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);",*/
        "z-index: 1 !important;",
        "}",
        ".theme1 button, .theme {",
        "background-color: black !important;",
        "color: white !important;",

        "text-align: center !important;",
        "text-decoration: none !important;",
        "display: inline-block !important;",
        "}",

        ".theme:hover .theme1 {",
        "display: block !important;",
        "background-color:black !important;",
        "}",
        ".theme h2 {",
        "border: 5px solid black !important;",
        " font-size: 10px !important;",
        "background-color:black !important;",
        "}",
        ".theme {",
        "margin-left: 20px !important;",
        "}",
    "#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm > div > div:nth-child(2) > div > span > span.mLCHD._1OSdk > button > div > span > svg {",//similar account
    "fill: white !important;",
    "}",
		"#react-root > section > main > div > div.NP414.ccgHY.GZkEI > div.Igw0E.IwRSH.eGOV_._4EzTm > div > button.Szr5J._6CZji > div,#react-root > section > main > div > div.NP414.ccgHY.GZkEI > div.Igw0E.IwRSH.eGOV_._4EzTm > div > button.Szr5J.POSa_ > div {",//more similar arrow
      "background: #4a4552a1 !important;",
    	"border-bottom-left-radius: 20px !important;",
    	"border-top-left-radius: 20px !important;",
    	"border-bottom-right-radius: 8px !important;",
    	"border-top-right-radius: 8px !important;",
        "}",
			"#react-root > section > main > div > div._4bSq7 > div > div > div > ul > * > div {",//highlighted stories
    "border-radius: 16px !important;",
    "background: #0f0e0e !important;",
"}",
			".MxEZm {",// explore
        "margin: 0 0 0 0 !important;",
        "max-width: 1675px !important;",
        "width: 1480px !important;",
        "}",
			"/*post hover */",
        ".qn-0x,.Ln-UN{",
        "background-color: rgba(0, 0, 0, 0)!important;",
        "}",

    ].join("\n");
var cssb = [
    " /* Full wide start */",

     "/Individual Post/ ",
	".ltEKP .QBXjJ{",
	"    border: none;",
	"}",
	"._8-yf5 [d=\"M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z\"]{",
	"	filter: invert(0) !important;",
	"    fill: #12B6A9 !important;",
	"}",
	".JyscU.ePUX4 .UE9AK{",
	"    background-color: var(--bg3-color) !important;",
	"    border-left: none;",
	"    border-bottom: none;",
	"}",
	".JyscU.ePUX4 .eo2As{",
	"    border-left: none;",
	"    border-top: none;",
	"}",
	".JyscU .Slqrh{",
	"    border-top: none;",
	"}",
	"",
	"._9AhH0 {",
	"    display: none;",
	"}",
	"",
	".PyenC, .fXIG0 {",
	"    height: 135px;",
	"    left: 50%;",
	"    margin-left: -67px;",
	"    margin-top: -67px;",
	"    top: 50%;",
	"    width: 135px;",
	"    z-index: 1;",
	"}",
	"",
	".PdwC2 {",
	"    max-width: 65% !important;",
	"    max-height: 100% !important;",
	"}",
	"",
	".JyscU ._97aPb,.eLAPa,.pR7Pc, .rQDP3  {",
	"    max-height: 100% !important;",
	"}",
	".glyphsSpriteDirect__outline__24__grey_9, .glyphsSpriteFacebook_circle__outline__24__grey_9, .glyphsSpriteFacebook_circle_filled_24, .glyphsSpriteApp_messenger__outline__24__grey_9, .glyphsSpriteApp_twitter__outline__24__grey_9, .glyphsSpriteMail__outline__24__grey_9, .glyphsSpriteLink__outline__24__grey_9, .glyphsSpriteLite_app_icon{",
	"    filter: invert(1);",
	"}",
	"",
    "/Individual Post/", 

    "body /* to even out with the scrollbar container width */ {",
    "    margin-left:6px;",
    "}",
    ".M9sTE  .L_LMM  .JyscU  .ePUX4{",
    "    width:100%!important;",
    "    max-width:none!important;",
    "    padding:0!important;",
    "    margin:2.5px 5px!important;",
    "}",
    "body /* roboto as font */ {",
    "    font-family:roboto;",
    "    text-rendering:geometricPrecision; ",
    "}",
    ".v9tJq /* stretches posts grid to the full width of the screen */ {",
    "    max-width:none!important;",
    "    padding:0!important;",
    "    width:100%!important;",
    "}",
    "._bz0w, .weEfm, .v9tJq  /* removes margins from posts */ {",
    "    margin:2.5px 5px!important;",
    "}",
    ":focus /* hides ugly blue outline from elements which are in focus currently */ {",
    "    outline:0;",
    "}",
    ".vtbgv /* adds a margin between sticky header and profile header */ {",
    "    margin-top:44px;",
    "}",
    ".aUCRo /* hides the sticky header when scrolling past profile header */, ._49XvD, .iHqQ7, .SkY6J /* hides stories, follow suggestions and instagram links from the homepage sidebar */ {",
    "    display:none;",
    "}",
    ".qqm6D /* centers higlights */ {",
    "    margin:0 auto;",
    "}",
	"#react-root > section > main > div > div._4bSq7 > div > div > div > ul > * > div {",//highlighted stories
  	  "border-radius: 16px !important;",
	"}",
	".KQA-S, ._1MzIy, ._3MPWk, ._8Rm4L, .zMhqu /* border radius for posts */,.Igw0E.rBNOH.eGOV_.ybXk5._4EzTm,.ItkAi,.tHaIX.Igw0E.IwRSH.eGOV_._4EzTm.HVWg4,.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a/*profile in homepage*/ {",
        "    border-radius:16px !important;",
	"}",
    ".JYWcJ, .JYWcJ:link, .JYWcJ:visited /* sets font weight to regular on photo tags */ {",
    "    font-weight:400;",
    "}",
    "  /* scrollbar css */",
    "  /* total width */",
    "::-webkit-scrollbar {width:6px}",
    "::-webkit-scrollbar:horizontal {height:6px}",
    "",
    "/* background of the scrollbar except button or resizer */",
    "::-webkit-scrollbar-track {background-color:rgba(50, 55, 87)}",
    "::-webkit-scrollbar-track:horizontal {background-color:rgba(50, 55, 87)}",
    "",
    "/* scrollbar itself */",
    "::-webkit-scrollbar-thumb {background-color:rgba(42, 52, 115);border-radius:16px;width:6px;transition:all 3s ease}",
    "::-webkit-scrollbar-thumb:hover {background-color:rgba(135, 141, 176)}",
    "",
    ".Igw0E,.rBNOH,.eGOV_,.ybXk5,._4EzTm,.XfCBB,.HVWg4,.IwRSH{",
    "background: rgb(0,6,51) !important;",
    "}",
    /*".uk0Yc,.GGDyX{",
    "background: #5461bf !important;",
    "}",*/
    "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div{",
    "padding:16px 16px !important;",
    "}",
    "",
    "/* set button(top and bottom of the scrollbar) */",
    "::-webkit-scrollbar-button {display:none}",
    " /* scrollbar css end */",
    " /* Full wide end */",
    "body{",
    "background: #000633 !important;",
    "}",
    ".-V_eO{",
    "opacity:0 !important;",
    "}",


    "/*fb and other icon*/",
    "FuWoR,.-wdIA,.x7xX2{",
    "background: #474769 !important;",
    "}",
    "",
    "/*variables 1*/",
    "",
    ".sDN5V {",
    "    /*variables modification*/",
    "    ",
    " /* the panels and the navigation bar  */ ",
    "    --d87: 0, 6, 51!important;",
    " /* background  */",
    "    --b3f: 10,15,57!important;",
    " /* general borders I think */",
    "    --b6a: 30,30,30!important;",
    " /* border that goes for photos */",
    "    --ce3: 30,30,30 !important;",
    " /* Name of the Stories */",
    "    --i1d: 255,255,255 !important;",
    " /* white bar in the activities part */",
    "    --f23: 0, 6, 51!important;",
    " /* likes */",
    "    --f75: 255,255,255;",
    " /* mention */",
    "    --fe0: 245,245,245 !important;",
    " /* I sew up the photos in the profiles */",
    "    --b38: 100,100,100 !important;",
    " /* chat selected */",
    "    --bb2: 10,15,57!important;",
    "",
    "    ",
    "    /*------------------------------*/",
    "    --edc: 199,199,199;",
    "    --ca6: 219,219,219;",
    "    --cdd: 0,6,51;",
    "    --e22: 199,199,199;",
    "    --e62: 245,251,255;",
    "    --b2f: 88,195,34;",
    "    --c8c: 168,168,168;",
    "    --jd9: 0, 6, 51;",
    "    --j64: 54,54,54;",
    "    --a97: 243,243,243;",
    "    --d20: 0,6,51;",
    "}",
    "",

    "/*Variables 2*/",
    ".ekjoN, .sDN5V {",
    "     /*variables modification*/",
    "",
    "    /*search bar */",
    "    --f52: 161,161,161 !important;",
    "	/*multimedia background */",
    "    --jb7: 10,10,10 !important;",
    "   /*when you share*/",
    "    --fa7: 27,41,52;",
    "",
    "",
    "	/*---------------------------------*/",
    "    --h1d: 255,255,255;",
    "    --de5: 255,255,255;",
    "    --d69: 0,149,246;",
    "    --b86: 88,195,34;",
    "    --i30: 237,73,86;",
    "    --d62: 255,255,255;",
    "    --e4f: 54,54,54;",
    "    --a72: 255,255,255;",
    "    --ie3: 142,142,142;",
    "    --c37: 237,73,86;",
    "    --f24: 0,149,246;",
    "    --jbb: 53,121,234;",
    "    --eca: 255,255,255;",
    "    --ba8: 168,168,168;",
    "    --eac: 237,73,86;",
    "}",
    "/*Homepage*/",
    "",
    "",
    "",
    "/*scroll bar*/",
    "",
    "*::-webkit-scrollbar {",
    "	width: 15px;",
    "	background:#121212;",
    "",
    "}",
    "",
    "*::-webkit-scrollbar-thumb {",
    "	background: rgba(255,255,255,.3);",
    "}",
    "",
    "/*LOGO*/",
    ".s4Iyt {",
    "    filter: invert(1) !important;",
    "}",
    "",
    "/*three dots of more options and the other icons on the navigation bar*/",
    "",
    "",
    "a > ._8-yf5 {",
    "    fill: rgb(255,255,255) !important;",
    "}",
    "div > ._8-yf5 {",
    "    fill: rgb(255,255,255) !important;",
    "}",
    "",
    "",
    "/*los MEGUSTA */",
    "span svg[aria-label=\"Me gusta\"], span svg[aria-label=\"Like\"], span svg[aria-label=\"Hou van\"], span svg[aria-label=\"To se mi líbí\"], span svg[aria-label=\"Synes godt om\"], span svg[aria-label=\"Gefällt mir\"], span svg[aria-label=\"Μου αρέσει!\"], span svg[aria-label=\"Tykkää\"], span svg[aria-label=\"J’aime\"], span svg[aria-label=\"Suka\"], span svg[aria-label=\"Mi piace\"], span svg[aria-label=\"いいね！\"], span svg[aria-label=\"좋아요\"], span svg[aria-label=\"Liker\"], span svg[aria-label=\"Vind ik leuk\"], span svg[aria-label=\"Lubię to!\"], span svg[aria-label=\"Curtir\"], span svg[aria-label=\"Gosto\"], span svg[aria-label=\"Нравится\"], span svg[aria-label=\"Gilla\"], span svg[aria-label=\"ถูกใจ\"], span svg[aria-label=\"I-like\"], span svg[aria-label=\"Beğen\"], span svg[aria-label=\"赞\"], span svg[aria-label=\"讚\"], span svg[aria-label=\"লাইক\"], span svg[aria-label=\"પસંદ\"], span svg[aria-label=\"लाइक करें\"], span svg[aria-label=\"Sviđa mi se\"], span svg[aria-label=\"Tetszik\"], span svg[aria-label=\"ಇಷ್ಟ\"], span svg[aria-label=\"ലൈക്കുചെയ്യുക\"], span svg[aria-label=\"पसंत करा\"], span svg[aria-label=\"मनपराउनुहोस्\"], span svg[aria-label=\"ਪਸੰਦ ਕਰੋ\"], span svg[aria-label=\"කැමැත්ත\"], span svg[aria-label=\"Páči sa mi to\"], span svg[aria-label=\"விருப்பம்\"], span svg[aria-label=\"ఇష్టం\"], span svg[aria-label=\"Thích\"], span svg[aria-label=\"讚好\"], span svg[aria-label=\"Харесва ми\"], span svg[aria-label=\"Îmi place\"], span svg[aria-label=\"Свиђа ми се\"], span svg[aria-label=\"Подобається\"]{",
    " fill: rgb(255,255,255) !important;",
    "}",
    "",
    "/*.QBdPU > svg[aria-label=\"Me gusta\"], .QBdPU > svg[aria-label=\"Like\"]{",
    " fill: rgb(255,255,255) !important;",
    "}*/",
    "",
    ".ZyFrc> svg{",
    " fill: rgb(237, 73, 86) !important;",
    "}",
    "",
    "",
    "/*search bar*/",
    ".Di7vw {",
    "    background: #415382 !important;",
    "}",
    ".x3qfX {",
    "  background: #415382 !important;",
    "}",
    "",
    "/*mute video*/",
    ".IhCmn > svg{",
    "    fill: #415382 !important;",
    "}",
    "",
    "",
    "/*perfiles*/",
    "",
    "",
    "/*buttons*/",
    "span button.-fzfL {",
    "    border-color: #fff !important;",
    "}",
    ".glyphsSpriteFriend_Follow{",
    " filter: invert(1) !important;",
    "}",
    ".coreSpriteDropdownArrowGrey9{",
    " filter: invert(1) !important;",
    "}",
    "",
    "",
    ".RnEpo {",
    "    background-color: #0a0f39;",
    "}",
    "",
    "",
    "a, button,h2,span{",
    "    color: #ffffff !important;",
    "}",
    "",
    "/*posts*/",
    ".IhCmn {",
    "    background-color: #fff !important;",
    "}",
    "/* Big following list */",
    "body > div.RnEpo.Yx5HN > div{",
    "    max-height: 2200px !important;",
    "}",
    "span._2dbep,a._2dbep.qNELH.kIKUG{",
    "    width: 80px !important;",
    "    height: 80px !important;",
    "}",
    "canvas.CfWVH{",
    "    width: 90px !important;",
    "    height: 90px !important;",
    "}",
    "#react-root > section > main > div > header > div > div > span {",
    "    width: 150px !important;",
    "    height: 150px !important;",
    "}",
    "#react-root > section > main > div > header > div > div > canvas{",
    "    width: 168px !important;",
    "    height: 168px !important;",
    "}",
    "#react-root > section > div > div._lz6s.Hz2lF > div > div.ctQZg > div > div:nth-child(5) > span,#react-root > section > nav > div._8MQSO.Cx7Bp > div > div > div.ctQZg > div > div:nth-child(5) > span{",
    "    width: 22px !important;",
    "    height: 22px !important;",
    "}",
    "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > canvas{",
    "    width: 66px !important;",
    "    height: 66px !important;",
    "}",
    "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > a > img,#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > a{",
    "    width: 56px !important;",
    "    height: 56px !important;",
    "}",
    "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div._8UZ6e > div.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a > div > div > div > * > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > div > canvas{",
    "    width: 44px !important;",
    "    height: 44px !important;",
    "}",
    "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div._8UZ6e > div.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a > div > div > div > * > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > div > a,#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div._8UZ6e > div.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a > div > div > div > * > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > div > span{",
    "    width: 32px !important;",
    "    height: 32px !important;",
    "}",
    "#react-root > section > main > section > div.cGcGK > * > div > * > div.eo2As > section.EDfFK.ygqzn > div > div.Igw0E._56XdI.eGOV_._4EzTm.ItkAi > a > div > div > span,body > div._2dDPU.CkGkG > div.zZYga > div > article > div.eo2As > section.EDfFK.ygqzn > div > div.Igw0E._56XdI.eGOV_._4EzTm.ItkAi > a > div > div > span{",
    "    width: 20px !important;",
    "    height: 20px !important;",
    "}",

    ".theme {",
    "background-color: rgb(20, 26, 71) !important;",
    " position: relative !important;",
    "display: inline-block !important;",
    "}",

    ".theme1 {",
    "width: 100% !important;",
    "display: none !important;",
    "position: absolute !important;",
    "background-color: rgb(20, 26, 71) !important;",
    "min-width: 7px !important;",
    "z-index: 1 !important;",
    "}",
    ".theme1 button, .theme {",

    "background-color: rgb(20, 26, 71) !important;",
    "color: white !important;",
    "text-align: center !important;",
    "text-decoration: none !important;",
    "display: inline-block !important;",
    "}",

    ".theme:hover .theme1 {",
    "display: block !important;",
    "background-color:rgb(20, 26, 71) !important;",
    "}",
    ".theme h2 {",
    "border: 5px solid rgb(20, 26, 71)  !important;",
    " font-size: 10px !important;",
    "background-color:rgb(20, 26, 71)  !important;",
    "}",
    ".theme {",
    "margin-left: 20px !important;",
    "}",
    "#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm > div > div > div > span > span.mLCHD._1OSdk > button > div {",//similar account
    "background-color: #2196f3 !important;",
    "}",
    "#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm > div > div:nth-child(2) > div > span > span.mLCHD._1OSdk > button > div > span > svg {",//similar account
    "fill: white !important;",
    "}",
		"#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm > div > div:nth-child(2) > div > span > span.mLCHD._1OSdk > button > div {",//similar account
    "background-color: #20183000 !important;",
    "}",
	"/*post hover */",
    ".qn-0x,.Ln-UN{",
    "background-color: rgba(0, 0, 0, 0)!important;",
    "}",
	
			".MxEZm {",// explore
        "margin: 0 0 0 0 !important;",
        "max-width: 1675px !important;",
        "width: 1480px !important;",
        "}",
		
].join("\n");
var cssn = [
    " /* Full wide start */",

    "/*Individual Post*/",
    ".ltEKP .QBXjJ{",
    "    border: none;",
    "}",
    "._8-yf5 [d=\"M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z\"]{",
    "	filter: invert(0) !important;",
    "    fill: #12B6A9 !important;",
    "}",
    ".JyscU.ePUX4 .UE9AK{",
    "    background-color: var(--bg3-color) !important;",
    "    border-left: none;",
    "    border-bottom: none;",
    "}",
    ".JyscU.ePUX4 .eo2As{",
    "    border-left: none;",
    "    border-top: none;",
    "}",
    ".JyscU .Slqrh{",
    "    border-top: none;",
    "}",
    "",
    "._9AhH0 {",
    "    display: none;",
    "}",
    "",
    ".PyenC, .fXIG0 {",
    "    height: 135px;",
    "    left: 50%;",
    "    margin-left: -67px;",
    "    margin-top: -67px;",
    "    top: 50%;",
    "    width: 135px;",
    "    z-index: 1;",
    "}",
    "",
    ".PdwC2 {",
    "    max-width: 65% !important;",
    "    max-height: 100% !important;",
    "}",
    "",
    ".JyscU ._97aPb,.eLAPa,.pR7Pc, .rQDP3  {",
    "    max-height: 100% !important;",
    "}",
    ".glyphsSpriteDirect__outline__24__grey_9, .glyphsSpriteFacebook_circle__outline__24__grey_9, .glyphsSpriteFacebook_circle_filled_24, .glyphsSpriteApp_messenger__outline__24__grey_9, .glyphsSpriteApp_twitter__outline__24__grey_9, .glyphsSpriteMail__outline__24__grey_9, .glyphsSpriteLink__outline__24__grey_9, .glyphsSpriteLite_app_icon{",
    "    filter: invert(1);",
    "}",
    "",
    ".-V_eO{",
    "opacity:0 !important;",
    "}",
    "/*Individual Post*/",

    "body /* to even out with the scrollbar container width */ {",
    "    margin-left:6px;",
    "}",
    ".M9sTE  .L_LMM  .JyscU  .ePUX4{",
    "    width:100%!important;",
    "    max-width:none!important;",
    "    padding:0!important;",
    "    margin:2.5px 5px!important;",
    "}",
    "body /* roboto as font */ {",
    "    font-family:roboto;",
    "    text-rendering:geometricPrecision; ",
    "}",
    ".v9tJq /* stretches posts grid to the full width of the screen */ {",
    "    max-width:none!important;",
    "    padding:0!important;",
    "    width:100%!important;",
    "}",
    "._bz0w, .weEfm, .v9tJq  /* removes margins from posts */ {",
    "    margin:2.5px 5px!important;",
    "}",
    ":focus /* hides ugly blue outline from elements which are in focus currently */ {",
    "    outline:0;",
    "}",
    ".vtbgv /* adds a margin between sticky header and profile header */ {",
    "    margin-top:44px;",
    "}",
    ".aUCRo /* hides the sticky header when scrolling past profile header */, ._49XvD, .iHqQ7, .SkY6J /* hides stories, follow suggestions and instagram links from the homepage sidebar */ {",
    "    display:none;",
    "}",
    ".qqm6D /* centers higlights */ {",
    "    margin:0 auto;",
    "}",
    ".KQA-S, ._1MzIy, ._3MPWk, ._8Rm4L, .zMhqu /* border radius for posts */ {",
    "    border-radius:16px;",
    "}",
    ".JYWcJ, .JYWcJ:link, .JYWcJ:visited /* sets font weight to regular on photo tags */ {",
    "    font-weight:400;",
    "}",
    "  /* scrollbar css */",
    "  /* total width */",
    "::-webkit-scrollbar {width:6px}",
    "::-webkit-scrollbar:horizontal {height:6px}",
    "",
    "/* background of the scrollbar except button or resizer */",
    "::-webkit-scrollbar-track {background-color:rgba(232,232,232,.2)}",
    "::-webkit-scrollbar-track:horizontal {background-color:rgba(232,232,232,.2)}",
    "",
    "/* scrollbar itself */",
    "::-webkit-scrollbar-thumb {background-color:rgba(152,152,152);border-radius:16px;width:6px;transition:all 3s ease}",
    "::-webkit-scrollbar-thumb:hover {background-color:rgba(104,104,104)}",
    "",
    "/* set button(top and bottom of the scrollbar) */",
    "::-webkit-scrollbar-button {display:none}",
    " /* scrollbar css end */",
    " /* Full wide end */",
    "}",
    "/* Big following list */",
    "body > div.RnEpo.Yx5HN > div{",
    "    max-height: 2200px !important;",
    "}",
    "span._2dbep,a._2dbep.qNELH.kIKUG{",
    "    width: 80px !important;",
    "    height: 80px !important;",
    "}",
    "canvas.CfWVH{",
    "    width: 90px !important;",
    "    height: 90px !important;",
    "}",
    "#react-root > section > main > div > header > div > div > span {",
    "    width: 150px !important;",
    "    height: 150px !important;",
    "}",
    "#react-root > section > main > div > header > div > div > canvas{",
    "    width: 168px !important;",
    "    height: 168px !important;",
    "}",
    "#react-root > section > div > div._lz6s.Hz2lF > div > div.ctQZg > div > div:nth-child(5) > span,#react-root > section > nav > div._8MQSO.Cx7Bp > div > div > div.ctQZg > div > div:nth-child(5) > span{",
    "    width: 22px !important;",
    "    height: 22px !important;",
    "}",
    "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > canvas{",
    "    width: 66px !important;",
    "    height: 66px !important;",
    "}",
    "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > a > img,#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div.m0NAq.xrWdL > div > div > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > a{",
    "    width: 56px !important;",
    "    height: 56px !important;",
    "}",
    "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div._8UZ6e > div.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a > div > div > div > * > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > div > canvas{",
    "    width: 44px !important;",
    "    height: 44px !important;",
    "}",
    "#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div._8UZ6e > div.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a > div > div > div > * > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > div > a,#react-root > section > main > section > div.COOzN.MnWb5.YT6rB > div._8UZ6e > div.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_.WKY0a > div > div > div > * > div.Igw0E.IwRSH.eGOV_._4EzTm.yC0tu > div > div > span{",
    "    width: 32px !important;",
    "    height: 32px !important;",
    "}",
    "#react-root > section > main > section > div.cGcGK > * > div > * > div.eo2As > section.EDfFK.ygqzn > div > div.Igw0E._56XdI.eGOV_._4EzTm.ItkAi > a > div > div > span,body > div._2dDPU.CkGkG > div.zZYga > div > article > div.eo2As > section.EDfFK.ygqzn > div > div.Igw0E._56XdI.eGOV_._4EzTm.ItkAi > a > div > div > span{",
    "    width: 20px !important;",
    "    height: 20px !important;",
    "}",
    "#react-root > section > main > section > div.cGcGK > div.zGtbP.IPQK5.VideM > div > div > div > div > ul > * > div > button > div.eebAO.h_uhZ{",
    "    text-shadow: 2px 1px 2px #ffffff !important;",
    "    color: rgba(0,0,0) !important;",
    "}",
    ".theme {",
    "background-color: #CDCFDA  !important;",
    " position: relative !important;",
    "display: inline-block !important;",
    "}",

    ".theme1 {",
    "width: 100% !important;",
    "display: none !important;",
    "position: absolute !important;",
    "background-color: #CDCFDA  !important;",
    "min-width: 7px !important;",
    "box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);",
    "z-index: 1 !important;",
    "}",
    ".theme1 button, .theme {",

    "background-color: #CDCFDA  !important;",
    "color: black !important;",
    "text-align: center !important;",
    "text-decoration: none !important;",
    "display: inline-block !important;",
    "}",

    ".theme:hover .theme1 {",
    "display: block !important;",
    "background-color:#CDCFDA  !important;",
    "}",
    ".theme h2 {",
    "border: 5px solid #CDCFDA  !important;",
    " font-size: 10px !important;",
    "background-color:#CDCFDA  !important;",
    "}",
    ".theme {",
    "margin-left: 20px !important;",
    "}",
	"/*post hover */",
    ".qn-0x,.Ln-UN{",
    "background-color: rgba(0, 0, 0, 0)!important;",
    "}",
	
			".MxEZm {",// explore
        "margin: 0 0 0 0 !important;",
        "max-width: 1675px !important;",
        "width: 1480px !important;",
        "}",

].join("\n");}
    var themex=localStorage.getItem("num2");
    if(themex==null){themex=1;}
    if(themex==1){css=cssd}
    else if(themex==2){css=cssb}
    else if(themex==3){css=cssn}
		if (typeof GM_addStyle != "undefined") {
                       GM_addStyle(css);
                   } else if (typeof PRO_addStyle != "undefined") {
                       PRO_addStyle(css);
                   } else if (typeof addStyle != "undefined") {
                       addStyle(css);
                   } else {
                       var node = document.createElement("style");
                       node.type = "text/css";
                       node.appendChild(document.createTextNode(css));
                       var heads = document.getElementsByTagName("head");
                       if (heads.length > 0) {
                           heads[0].appendChild(node);
                       } else {
                           // no head yet, stick it whereever
                           document.documentElement.appendChild(node);
                       }
                   }


})();
